# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.mainTabs = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.mainTabs.setObjectName("mainTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 831, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.miner_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.miner_name.setObjectName("miner_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.miner_name)
        self.os = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.os.setReadOnly(True)
        self.os.setObjectName("os")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.os)
        self.miner_id = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.miner_id.setObjectName("miner_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.miner_id)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.miner_config = QtWidgets.QTreeWidget(self.verticalLayoutWidget_2)
        self.miner_config.setObjectName("miner_config")
        item_0 = QtWidgets.QTreeWidgetItem(self.miner_config)
        item_0 = QtWidgets.QTreeWidgetItem(self.miner_config)
        item_0 = QtWidgets.QTreeWidgetItem(self.miner_config)
        item_0 = QtWidgets.QTreeWidgetItem(self.miner_config)
        self.verticalLayout_2.addWidget(self.miner_config)
        self.mainTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 841, 501))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.api_endpoint = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.api_endpoint.setObjectName("api_endpoint")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.api_endpoint)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.api_use_iam = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.api_use_iam.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.api_use_iam.setChecked(True)
        self.api_use_iam.setObjectName("api_use_iam")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.api_use_iam)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.api_connect = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.api_connect.setObjectName("api_connect")
        self.horizontalLayout.addWidget(self.api_connect)
        self.api_disconnect = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.api_disconnect.setObjectName("api_disconnect")
        self.horizontalLayout.addWidget(self.api_disconnect)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enable_api = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.enable_api.setObjectName("enable_api")
        self.horizontalLayout_2.addWidget(self.enable_api)
        self.enable_remote_cmd = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.enable_remote_cmd.setObjectName("enable_remote_cmd")
        self.horizontalLayout_2.addWidget(self.enable_remote_cmd)
        self.enable_remote_config = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.enable_remote_config.setObjectName("enable_remote_config")
        self.horizontalLayout_2.addWidget(self.enable_remote_config)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.api_status_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.api_status_2.setObjectName("api_status_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.api_status_2)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.mainTabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 841, 501))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.miner_select = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.miner_select.setObjectName("miner_select")
        self.miner_select.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.miner_select)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777210))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 831, 452))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.XMR_PAYMENT_ADDR = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_PAYMENT_ADDR.setObjectName("XMR_PAYMENT_ADDR")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.XMR_PAYMENT_ADDR)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.XMR_PASSWORD = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_PASSWORD.setText("")
        self.XMR_PASSWORD.setObjectName("XMR_PASSWORD")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.XMR_PASSWORD)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.XMR_CPU_ENABLE = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_CPU_ENABLE.setChecked(True)
        self.XMR_CPU_ENABLE.setObjectName("XMR_CPU_ENABLE")
        self.horizontalLayout_3.addWidget(self.XMR_CPU_ENABLE)
        self.XMR_CPU_AS = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_CPU_AS.setObjectName("XMR_CPU_AS")
        self.horizontalLayout_3.addWidget(self.XMR_CPU_AS)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.XMR_CPU_THREADS = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_CPU_THREADS.setObjectName("XMR_CPU_THREADS")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.XMR_CPU_THREADS)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.XMR_CPU_MAX = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_CPU_MAX.setObjectName("XMR_CPU_MAX")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.XMR_CPU_MAX)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.XMR_NV_ENABLE = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_NV_ENABLE.setObjectName("XMR_NV_ENABLE")
        self.horizontalLayout_4.addWidget(self.XMR_NV_ENABLE)
        self.XMR_NV_AS = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_NV_AS.setObjectName("XMR_NV_AS")
        self.horizontalLayout_4.addWidget(self.XMR_NV_AS)
        self.formLayout_4.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.XMR_NV_THREADS = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_NV_THREADS.setObjectName("XMR_NV_THREADS")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.XMR_NV_THREADS)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.XMR_NV_BLOCKS = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_NV_BLOCKS.setObjectName("XMR_NV_BLOCKS")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.XMR_NV_BLOCKS)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.XMR_AMD_ENABLE = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_AMD_ENABLE.setObjectName("XMR_AMD_ENABLE")
        self.horizontalLayout_5.addWidget(self.XMR_AMD_ENABLE)
        self.XMR_AMD_AS = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.XMR_AMD_AS.setObjectName("XMR_AMD_AS")
        self.horizontalLayout_5.addWidget(self.XMR_AMD_AS)
        self.formLayout_4.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.XMR_AMD_INTENSITY = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_AMD_INTENSITY.setObjectName("XMR_AMD_INTENSITY")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.XMR_AMD_INTENSITY)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.XMR_AMD_WORKSIZE = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.XMR_AMD_WORKSIZE.setObjectName("XMR_AMD_WORKSIZE")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.XMR_AMD_WORKSIZE)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.mainTabs.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 841, 501))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_7)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 831, 471))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.XMR_URL0 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL0.setObjectName("XMR_URL0")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.XMR_URL0)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.XMR_URL1 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL1.setObjectName("XMR_URL1")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.XMR_URL1)
        self.XMR_URL2 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL2.setObjectName("XMR_URL2")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.XMR_URL2)
        self.XMR_URL3 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL3.setObjectName("XMR_URL3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.XMR_URL3)
        self.XMR_URL4 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL4.setObjectName("XMR_URL4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.XMR_URL4)
        self.XMR_URL5 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL5.setObjectName("XMR_URL5")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.XMR_URL5)
        self.XMR_URL6 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL6.setObjectName("XMR_URL6")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.XMR_URL6)
        self.XMR_URL7 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL7.setObjectName("XMR_URL7")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.XMR_URL7)
        self.XMR_URL8 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL8.setObjectName("XMR_URL8")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.XMR_URL8)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.XMR_URL9 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.XMR_URL9.setObjectName("XMR_URL9")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.XMR_URL9)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.mainTabs.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 841, 506))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_32.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CPU_RUN = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.CPU_RUN.setObjectName("CPU_RUN")
        self.horizontalLayout_7.addWidget(self.CPU_RUN)
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.CPU_HS = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.CPU_HS.setMinimumSize(QtCore.QSize(150, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 63, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.CPU_HS.setPalette(palette)
        self.CPU_HS.setDigitCount(6)
        self.CPU_HS.setProperty("value", 100000.0)
        self.CPU_HS.setObjectName("CPU_HS")
        self.horizontalLayout_7.addWidget(self.CPU_HS)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_34.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.NV_RUN = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.NV_RUN.setObjectName("NV_RUN")
        self.horizontalLayout_8.addWidget(self.NV_RUN)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.NV_HS = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.NV_HS.setMinimumSize(QtCore.QSize(150, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.NV_HS.setPalette(palette)
        self.NV_HS.setDigitCount(6)
        self.NV_HS.setProperty("value", 100000.0)
        self.NV_HS.setObjectName("NV_HS")
        self.horizontalLayout_8.addWidget(self.NV_HS)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_35.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.AMD_RUN = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.AMD_RUN.setObjectName("AMD_RUN")
        self.horizontalLayout_9.addWidget(self.AMD_RUN)
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_9.addWidget(self.label_37)
        self.AMD_HS = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.AMD_HS.setMinimumSize(QtCore.QSize(150, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.AMD_HS.setPalette(palette)
        self.AMD_HS.setDigitCount(6)
        self.AMD_HS.setProperty("value", 100000.0)
        self.AMD_HS.setObjectName("AMD_HS")
        self.horizontalLayout_9.addWidget(self.AMD_HS)
        self.formLayout_6.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_38 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_38.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.T_HS = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.T_HS.setMinimumSize(QtCore.QSize(250, 100))
        self.T_HS.setDigitCount(6)
        self.T_HS.setProperty("value", 100000.0)
        self.T_HS.setObjectName("T_HS")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.T_HS)
        self.label_39 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_39.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.H_HS = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.H_HS.setMinimumSize(QtCore.QSize(250, 100))
        self.H_HS.setDigitCount(6)
        self.H_HS.setProperty("value", 100000.0)
        self.H_HS.setObjectName("H_HS")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.H_HS)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.RUN_ALL = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.RUN_ALL.setObjectName("RUN_ALL")
        self.horizontalLayout_11.addWidget(self.RUN_ALL)
        self.STOP_ALL = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.STOP_ALL.setObjectName("STOP_ALL")
        self.horizontalLayout_11.addWidget(self.STOP_ALL)
        self.SYNC_CONFIG = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.SYNC_CONFIG.setObjectName("SYNC_CONFIG")
        self.horizontalLayout_11.addWidget(self.SYNC_CONFIG)
        self.formLayout_6.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.formLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.MINER_LOG = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        self.MINER_LOG.setReadOnly(True)
        self.MINER_LOG.setObjectName("MINER_LOG")
        self.verticalLayout_5.addWidget(self.MINER_LOG)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.mainTabs.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.mainTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_MinerNode = QtWidgets.QAction(MainWindow)
        self.actionAbout_MinerNode.setObjectName("actionAbout_MinerNode")
        self.action_Visit_MinerCloud = QtWidgets.QAction(MainWindow)
        self.action_Visit_MinerCloud.setObjectName("action_Visit_MinerCloud")
        self.actionImport_Config = QtWidgets.QAction(MainWindow)
        self.actionImport_Config.setObjectName("actionImport_Config")
        self.actionExport_Config = QtWidgets.QAction(MainWindow)
        self.actionExport_Config.setObjectName("actionExport_Config")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionImport_Config)
        self.menuFile.addAction(self.actionExport_Config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout_MinerNode)
        self.menuAbout.addAction(self.action_Visit_MinerCloud)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Miner Control"))
        self.label.setText(_translate("MainWindow", "MinerNode: Mine Smart!"))
        self.label_2.setText(_translate("MainWindow", "Miner ID (MAC Address):"))
        self.label_4.setText(_translate("MainWindow", "OS:"))
        self.label_3.setText(_translate("MainWindow", "Miner Name :"))
        self.miner_config.headerItem().setText(0, _translate("MainWindow", "Miner Configuration"))
        __sortingEnabled = self.miner_config.isSortingEnabled()
        self.miner_config.setSortingEnabled(False)
        self.miner_config.topLevelItem(0).setText(0, _translate("MainWindow", "Platform"))
        self.miner_config.topLevelItem(1).setText(0, _translate("MainWindow", "CPU(s)"))
        self.miner_config.topLevelItem(2).setText(0, _translate("MainWindow", "NV GPU(s)"))
        self.miner_config.topLevelItem(3).setText(0, _translate("MainWindow", "AMD GPU(s)"))
        self.miner_config.setSortingEnabled(__sortingEnabled)
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab), _translate("MainWindow", "Miner ID / Hardware Config"))
        self.label_6.setText(_translate("MainWindow", "MinerCloud API:"))
        self.label_5.setText(_translate("MainWindow", "Remote Endpoint:"))
        self.api_endpoint.setText(_translate("MainWindow", "https://minerCloud.api-gateway.com/api/"))
        self.label_9.setText(_translate("MainWindow", "Use MinerCloud Key:"))
        self.api_use_iam.setText(_translate("MainWindow", "Enable"))
        self.label_10.setText(_translate("MainWindow", "Connection Control:"))
        self.api_connect.setText(_translate("MainWindow", "Connect"))
        self.api_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.label_11.setText(_translate("MainWindow", "Connection Status:"))
        self.enable_api.setText(_translate("MainWindow", "Enable Remote Connection"))
        self.enable_remote_cmd.setText(_translate("MainWindow", "Accept Remote Commands"))
        self.enable_remote_config.setText(_translate("MainWindow", "Accept Remote Configuration"))
        self.api_status_2.setText(_translate("MainWindow", "Remote connection is disabled."))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_2), _translate("MainWindow", "MinerCloud API"))
        self.label_8.setText(_translate("MainWindow", "Currency and Miner:"))
        self.miner_select.setItemText(0, _translate("MainWindow", "XMR/XMRIG"))
        self.label_40.setText(_translate("MainWindow", "Payment ID/User:"))
        self.XMR_PAYMENT_ADDR.setText(_translate("MainWindow", "4a..."))
        self.label_42.setText(_translate("MainWindow", "Password:"))
        self.label_12.setText(_translate("MainWindow", "CPU Miner:"))
        self.XMR_CPU_ENABLE.setText(_translate("MainWindow", "Enabled"))
        self.XMR_CPU_AS.setText(_translate("MainWindow", "Auto Start"))
        self.label_13.setText(_translate("MainWindow", "CPU Miner Threads:"))
        self.XMR_CPU_THREADS.setText(_translate("MainWindow", "4"))
        self.label_14.setText(_translate("MainWindow", "CPU Miner MAX CPU:"))
        self.XMR_CPU_MAX.setText(_translate("MainWindow", "95"))
        self.label_17.setText(_translate("MainWindow", "NV Miner:"))
        self.XMR_NV_ENABLE.setText(_translate("MainWindow", "Enabled"))
        self.XMR_NV_AS.setText(_translate("MainWindow", "Auto Start"))
        self.label_16.setText(_translate("MainWindow", "NV Miner Threads:"))
        self.XMR_NV_THREADS.setText(_translate("MainWindow", "20"))
        self.label_15.setText(_translate("MainWindow", "NV Miner Blocks:"))
        self.XMR_NV_BLOCKS.setText(_translate("MainWindow", "24"))
        self.label_18.setText(_translate("MainWindow", "AMD Miner:"))
        self.XMR_AMD_ENABLE.setText(_translate("MainWindow", "Enabled"))
        self.XMR_AMD_AS.setText(_translate("MainWindow", "Auto Start"))
        self.label_20.setText(_translate("MainWindow", "AMD Miner Intensity:"))
        self.XMR_AMD_INTENSITY.setText(_translate("MainWindow", "600"))
        self.label_19.setText(_translate("MainWindow", "AMD Miner Worksize:"))
        self.XMR_AMD_WORKSIZE.setText(_translate("MainWindow", "8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "XMR/XMRIG"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_3), _translate("MainWindow", "Miner Settings"))
        self.label_21.setText(_translate("MainWindow", "URL0:"))
        self.label_22.setText(_translate("MainWindow", "URL1:"))
        self.label_23.setText(_translate("MainWindow", "URL2:"))
        self.label_24.setText(_translate("MainWindow", "URL3:"))
        self.label_25.setText(_translate("MainWindow", "URL4:"))
        self.label_26.setText(_translate("MainWindow", "URL5:"))
        self.label_27.setText(_translate("MainWindow", "URL6:"))
        self.label_28.setText(_translate("MainWindow", "URL7:"))
        self.label_29.setText(_translate("MainWindow", "URL8:"))
        self.label_30.setText(_translate("MainWindow", "URL9:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "XMR"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_5), _translate("MainWindow", "Connection Settings"))
        self.label_32.setText(_translate("MainWindow", "CPU Miner:"))
        self.CPU_RUN.setText(_translate("MainWindow", "Start Miner"))
        self.label_33.setText(_translate("MainWindow", "Hashrate:"))
        self.label_34.setText(_translate("MainWindow", "NV GPU Miner:"))
        self.NV_RUN.setText(_translate("MainWindow", "Start Miner"))
        self.label_36.setText(_translate("MainWindow", "Hashrate:"))
        self.label_35.setText(_translate("MainWindow", "AMD GPU Miner:"))
        self.AMD_RUN.setText(_translate("MainWindow", "Start Miner"))
        self.label_37.setText(_translate("MainWindow", "Hashrate:"))
        self.label_38.setText(_translate("MainWindow", "Total:"))
        self.label_39.setText(_translate("MainWindow", "Highest:"))
        self.RUN_ALL.setText(_translate("MainWindow", "Start ALL"))
        self.STOP_ALL.setText(_translate("MainWindow", "Stop ALL"))
        self.SYNC_CONFIG.setText(_translate("MainWindow", "Sync Config Changes"))
        self.label_31.setText(_translate("MainWindow", "Miner Log:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab_6), _translate("MainWindow", "Miner Control"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuAbout.setTitle(_translate("MainWindow", "Abo&ut"))
        self.actionAbout_MinerNode.setText(_translate("MainWindow", "&About MinerNode"))
        self.action_Visit_MinerCloud.setText(_translate("MainWindow", " &Visit MinerCloud"))
        self.actionImport_Config.setText(_translate("MainWindow", "&Open Config"))
        self.actionExport_Config.setText(_translate("MainWindow", "&Save Config as"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))

