# METHODS to URL mappings for network i/o:
AUTH="registrar/auth/"
WARNING="monitoring/warning/"
ERROR="monitoring/error/"
TYPE="stats/type/"
TOTALS="stats/totals/"
SPEED="stats/speed/"
REM_STATQUERY="control/status/"
UPDATE_CFG="control/set/cfg/"
GET_CFG="control/get/cfg/"
STOP_NTF="control/notify/stop/"
START_NTF="control/notify/start/"
